const constants = {
  siteName: 'SDUT OJ',
  siteTitle: 'SDUT Online Judge',
  githubUrl: 'https://github.com/sdutacm/onlinejudge3',
  contactEmail: 'sdutacm@163.com',
  serviceStatusUrl: 'https://service-status.sdutacm.cn',
  accessTokenCookieName: 'access_token_openoj',
  imageDirPrefix: `${process.env.MEDIA_URL}/image/`,
  avatarUrlPrefix: `${process.env.MEDIA_URL}/image/avatars/`,
  bannerImageUrlPrefix: `${process.env.MEDIA_URL}/image/banner_images/`,
  requestTimeout: 60 * 1000,
  msgDuration: {
    success: 3,
    warn: 5,
    error: 5,
  },
  indicatorDisplayDelay: 250,
  modalAnimationDurationFade: 200,
  modalAnimationDurationShake: 400,
  modalAnimationDurationSwitch: 600,
  menuAnimationDurationFade: 300,
  switchAnimationDuration: 400,
  ranklistUpdateInterval: 15 * 1000,
  ratingStatusUpdateInterval: 2 * 1000,
  bgCheckSessionInterval: 60 * 1000,
  bgGetUnreadMessagesInterval: 10 * 60 * 1000,
  mobileBreakPoint: 768,
  navbarHeight: 64,
  setStatsUserMaxSelect: 1000,
  setStatsUserMaxSelectPermission: 5000,
  drawerAnimationDuration: 300 + 100,
};

export default constants;
