const constants = {
  siteName: 'SDUT OJ',
  siteTitle: 'SDUT OnlineJudge',
  accessTokenCookieName: 'access_token_openoj',
  // avatarUrlPrefix: 'http://127.0.0.1/tmp4oj/avatars/',
  // bannerImageUrlPrefix: 'http://127.0.0.1/tmp4oj/banner_images/',
  imageDirPrefix: '/image/',
  avatarUrlPrefix: '/image/avatars/',
  bannerImageUrlPrefix: '/image/banner_images/',
  requestTimeout: 60 * 1000,
  msgDuration: {
    success: 3,
    error: 5,
  },
  indicatorDisplayDelay: 250,
  modalAnimationDurationFade: 200,
  modalAnimationDurationShake: 400,
  modalAnimationDurationSwitch: 600,
  menuAnimationDurationFade: 300,
  switchAnimationDuration: 400,
  ranklistUpdateInterval: 30 * 1000,
  ratingStatusUpdateInterval: 2 * 1000,
  bgCheckSessionInterval: 60 * 1000,
  bgGetUnreadMessagesInterval: 10 * 60 * 1000,
  mobileBreakPoint: 768,
  navbarHeight: 64,
  setStatsUserMaxSelect: 1000,
  setStatsUserMaxSelectPermission: 5000,
  drawerAnimationDuration: 300,
};

export default constants;
