import React from 'react';
import { Icon } from 'antd';
import { getAiAuthorInfo } from '@/utils/aiAuthor';

export interface AiGeneratedInfoProps {
  aiAuthor?: string | null;
  className?: string;
}

const AiGeneratedInfo: React.FC<AiGeneratedInfoProps> = ({ aiAuthor, className = '' }) => {
  const { name, icon } = getAiAuthorInfo(aiAuthor);
  const ProviderIcon = icon;

  if (!name) {
    return null;
  }

  return (
    <div className={`ai-generated-info ${className}`}>
      <span>Generated by</span>
      {ProviderIcon && <Icon component={ProviderIcon} className="ai-generated-info-icon" />}
      <span>{name}</span>
    </div>
  );
};

export default AiGeneratedInfo;
