name: Build and Upload to CDN
on:
  push:
    branches:
      - master
jobs:
  build-and-upload:
    env:
      COS_SECRET_ID: ${{ secrets.COS_SECRET_ID }}
      COS_SECRET_KEY: ${{ secrets.COS_SECRET_KEY }}
      COS_BUCKET: ${{ secrets.COS_BUCKET }}
      COS_REGION: ${{ secrets.COS_REGION }}
      COS_TARGET_BASE: ${{ secrets.COS_TARGET_BASE }}
      CDN_URL: ${{ secrets.CDN_URL }}
      MEDIA_URL: ${{ secrets.MEDIA_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci --legacy-peer-deps --registry=https://registry.npmjs.org
      - run: npm run build:cdn
